### ISSUE TITLE
Payments tests

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/gamerhash-facade#126]
Scenarios:
- Partial payments
- [x] Multi-activity
- Check if gh application correctly shows earnings
- Check if counters are computed correctly
- [x] Validate if Provider earnings sum up to correct amounts
- [x] Play around with Jobs killing and check how payments system behaves
- [x] Are payment statuses set correctly

Continued

**Comment by staszek-krotki** [comment]
Multi activity:
- multiple activities ran sequentially sum up earnings
- multiple activities ran in parallel only affect number of requests

**Comment by staszek-krotki** [comment]
If the provider's and requestor's yagnas are allowed to process payments then everything is fine.
It is possible that payments are not processed correctly if the payment workflow is broken by one of the yagna nodes not available

**Comment by staszek-krotki** [comment]
Killing of jobs breaks counting of payments due.
If the runtime is broken then payments are not processed
