### ISSUE TITLE
Signed Payment confirmation

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/gamerhash-facade#44]
What:
- Modify `yagna` Requestor code to sign Payment structure and pass it together with signature to Provider
  - sign with the same priv key that signed transaction on blockchain

Acceptance criteria:
- Provider is able to retrieve signed struct from API

Details:
- add field with bytes (serialized payment struct). Serialization should be changed, currently #debug print is used. Take into consideration json canonical representation
- compatibility with current state has to be maintained

resolves: https://github.com/golemfactory/yagna/pull/3069
resolves: https://github.com/golemfactory/ya-client/pull/157

**Comment by staszek-krotki** [comment]
resolves: https://github.com/golemfactory/yagna/pull/3050

**Comment by staszek-krotki** [comment]
resolves: https://github.com/golemfactory/ya-client/pull/157
