### ISSUE TITLE
Implement payments validation

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/gamerhash-facade#46]
Why:
- Gamerhash needs to ensure that Providers are entitled to payments

What:
- Implement Payment structure validation to avoid frauds (interface: https://github.com/golemfactory/gamerhash-facade/issues/45)
- Follow conclusions from document: https://www.notion.so/golemnetwork/Payments-verification-bba3cecdaa95438e854f4a0e954867c4
- Signature validation + blockchain check if the transaction exists + check all payment confirmations for given transaction if the sum doesn't exceed the transaction amount

Yagna and c# code has to be compatible with serialization/deserialization
Two options:
- canonical binary compatibility (rust => c#)
- comparison of json representation

Interface is in Facade.
Implementation can be part of c# Golem project  (it will be used by gamerhash on the server side)

**Comment by staszek-krotki** [comment]
This will be solved by gamerhash
