### ISSUE TITLE
Report GPU information in Offer

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/gamerhash-facade#56]
What:
- Runtime should publish GPU information in Offer in the same way as `vm-nvidia` runtime does
- Spec: https://golemfactory.github.io/golem-architecture/gaps/gap-35_gpu_pci_capability/gap-35_gpu_pci_capability.html

If all information is not available, try to query from system minimal valuable subset.

**Comment by pwalski** [comment]
GH uses wrapper library over Nvidia public API. There is an relatively popular and actively supported Rust equivalent
https://crates.io/crates/nvml-wrapper
Instead of using Nvidia smi `exe` I will just use this library.
